#Automatikus adattisztítás tesztfutás után.
#Tue May 05 00:58:37 CEST 2026
auth_token=ff471ea9-5c2e-4b4c-98e7-89c16b4040e9
balance_id_aud=277686
balance_id_eur=277684
balance_id_gbp=277640
balance_id_huf=277981
balance_id_na=278640
balance_id_usd=277685
base_url=https\://api.wise-sandbox.com
expected_first_name=Rosa
expected_last_name=Maxwell
expected_profile_id=28698729
invalid_token=ff471ea9-5c2e-4b4c-98e7-89c16b4040f9
quote_id_insufficient=f3441513-7aa9-4270-ab85-ab2c6f352217
